# Generated by Django 3.2.12 on 2024-03-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scan',
        ),
    ]
