# Generated by Django 3.2.12 on 2024-03-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authm', '0002_delete_scan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_scan', models.CharField(max_length=32)),
                ('tipo_scan', models.CharField(max_length=32)),
                ('data_begin', models.DateField()),
            ],
        ),
    ]
