# Generated by Django 3.2.12 on 2024-03-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0004_scan_db_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan_db',
            name='scan_nr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scan_db',
            name='target',
            field=models.CharField(max_length=32),
        ),
    ]
