# Generated by Django 3.2.12 on 2024-03-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0005_auto_20240312_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan_db',
            name='scan_nr',
        ),
    ]
