# Generated by Django 3.2.12 on 2024-03-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0006_remove_scan_db_scan_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan_db',
            name='target',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
