# Generated by Django 3.2.12 on 2024-03-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0007_alter_scan_db_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan_db',
            old_name='nome_scan',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='scan_db',
            old_name='tipo_scan',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='scan_db',
            name='data_begin',
        ),
        migrations.RemoveField(
            model_name='scan_db',
            name='target',
        ),
    ]
