# Generated by Django 3.2.12 on 2024-03-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0008_auto_20240313_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan_db',
            name='password',
        ),
        migrations.RemoveField(
            model_name='scan_db',
            name='username',
        ),
        migrations.AddField(
            model_name='scan_db',
            name='data_begin',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='scan_db',
            name='nome_scan',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='scan_db',
            name='scan_nr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scan_db',
            name='target',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='scan_db',
            name='tipo_scan',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
