# Generated by Django 3.2.12 on 2024-03-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0009_auto_20240313_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan_db',
            name='data_begin',
        ),
        migrations.AddField(
            model_name='scan_db',
            name='data_inicio',
            field=models.DateField(null=True),
        ),
    ]
