# Generated by Django 4.2.11 on 2024-03-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0011_scan_db_comecou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan_db',
            name='comecou',
            field=models.BooleanField(null=True),
        ),
    ]
