# Generated by Django 5.0.3 on 2024-04-02 10:48

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0015_alter_scan_db_comecou'),
    ]

    operations = [
        migrations.CreateModel(
            name='parsing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portas_abertas', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
            ],
        ),
    ]
