# Generated by Django 5.0.3 on 2024-04-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0016_parsing'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsing',
            name='alvo',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='parsing',
            name='portas_abertas',
            field=models.CharField(max_length=65535, null=True),
        ),
    ]
