# Generated by Django 4.2.11 on 2024-04-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0017_parsing_alvo_alter_parsing_portas_abertas'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsing',
            name='domain',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='scan_db',
            name='max_agressi',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='scan_db',
            name='velo_nmap',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
