# Generated by Django 4.2.11 on 2024-04-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0019_scan_db_portas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan_db',
            name='portas',
        ),
        migrations.RemoveField(
            model_name='scan_db',
            name='tipo_scan',
        ),
        migrations.AddField(
            model_name='scan_db',
            name='port_scan',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='scan_db',
            name='serv_scan',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='scan_db',
            name='web_scan',
            field=models.BooleanField(null=True),
        ),
    ]
