# Generated by Django 4.2.11 on 2024-04-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0020_remove_scan_db_portas_remove_scan_db_tipo_scan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan_db',
            name='port_scan',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scan_db',
            name='serv_scan',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scan_db',
            name='web_scan',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
