# Generated by Django 4.2.11 on 2024-04-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0021_alter_scan_db_port_scan_alter_scan_db_serv_scan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parsing',
            old_name='alvo',
            new_name='ip',
        ),
        migrations.AddField(
            model_name='parsing',
            name='protocolo',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='parsing',
            name='servi',
            field=models.CharField(max_length=999, null=True),
        ),
    ]
