# Generated by Django 4.2.11 on 2024-04-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0022_rename_alvo_parsing_ip_parsing_protocolo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan_db',
            name='pingd',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='parsing',
            name='protocolo',
            field=models.CharField(max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='parsing',
            name='servi',
            field=models.CharField(max_length=9999, null=True),
        ),
    ]
