# Generated by Django 4.2.11 on 2024-04-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0024_scan_db_acabou'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15)),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='parsing',
        ),
    ]
