# Generated by Django 4.2.11 on 2024-04-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0026_scan_db_existe'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan_db',
            name='todas',
            field=models.BooleanField(default=False),
        ),
    ]
