# Generated by Django 4.2.11 on 2024-04-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0027_scan_db_todas'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan_db',
            name='ja_abertas',
            field=models.BooleanField(default=False),
        ),
    ]
