# Generated by Django 4.2.11 on 2024-04-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0029_scan_db_op_portas'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan_db',
            name='portas_ch',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
