# Generated by Django 5.0.4 on 2024-04-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0031_scanresult_delete_ipaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host_Re',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15)),
                ('hostname', models.CharField(max_length=100)),
                ('open_ports', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='ScanResult',
        ),
    ]
