# Generated by Django 5.0.4 on 2024-04-15 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0032_host_re_delete_scanresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host_re',
            name='hostname',
        ),
    ]
