# Generated by Django 5.0.4 on 2024-04-15 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0033_remove_host_re_hostname'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='authm.ipaddress')),
            ],
            options={
                'unique_together': {('ip_address', 'number')},
            },
        ),
        migrations.DeleteModel(
            name='Host_Re',
        ),
    ]
