# Generated by Django 3.2.19 on 2024-04-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0034_ipaddress_port_delete_host_re'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan_db',
            name='openvas',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
