# Generated by Django 3.2.12 on 2024-04-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0035_scan_db_openvas'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan_db',
            name='openvas_comecou',
            field=models.BooleanField(default=False),
        ),
    ]
