# Generated by Django 3.2.12 on 2024-05-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0037_final_ip_final_port_outputfinal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='final_ip',
        ),
        migrations.AddField(
            model_name='port',
            name='cve',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='port_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='severity',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='final_port',
        ),
    ]
