# Generated by Django 3.2.12 on 2024-06-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0041_auto_20240523_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='port_scan',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='serv_scan',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='web_scan',
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='portas',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.DeleteModel(
            name='CVE',
        ),
        migrations.DeleteModel(
            name='Port',
        ),
    ]
