# Generated by Django 3.2.12 on 2024-06-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0043_ipaddress_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='servicos',
            field=models.CharField(max_length=999, null=True),
        ),
    ]
