# Generated by Django 3.2.12 on 2024-06-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0044_ipaddress_servicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='os',
            field=models.CharField(max_length=999, null=True),
        ),
    ]
