# Generated by Django 3.2.12 on 2024-06-11 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0045_ipaddress_os'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='os',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='portas',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='servicos',
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='address',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('service', models.CharField(max_length=100, null=True)),
                ('version', models.CharField(max_length=100, null=True)),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='authm.ipaddress')),
            ],
        ),
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cves', to='authm.port')),
            ],
        ),
    ]
