# Generated by Django 3.2.12 on 2024-06-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0046_auto_20240611_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='address',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
