# Generated by Django 3.2.19 on 2024-06-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0049_auto_20240611_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='ip',
            field=models.GenericIPAddressField(null=True, unique=True),
        ),
    ]
