# Generated by Django 3.2.19 on 2024-06-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0050_alter_ipaddress_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan_db',
            old_name='openvas',
            new_name='dorks',
        ),
        migrations.RemoveField(
            model_name='scan_db',
            name='openvas_comecou',
        ),
        migrations.AddField(
            model_name='scan_db',
            name='nuclei',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='scan_db',
            name='web_fuzz',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
