# Generated by Django 3.2.19 on 2024-06-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authm', '0051_auto_20240617_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='domain',
            field=models.CharField(max_length=999, null=True),
        ),
    ]
